### PR TITLE
Fix cpp-qt-client library

### PR DESCRIPTION
**Pull request by dschmidt**

### CODE REVIEW

**Comment by micbar** [comment]
@dschmidt can you rebase? I think the changes to the golang code is unreleated to your PR.

**Comment by micbar** [comment]
This is no fun. Seems that the openapi-generator:latest is different than your version. Can you update our generator to latest?

**Comment by dschmidt** [comment]
Done.

**Review by micbar — APPROVED** [review]
Awesome!

**Comment by dschmidt** [comment]
🚀

**Pull request merged**
