### PR TITLE
enhancement: add permission client sync prop

### PR DESCRIPTION
**Pull request by fschade**
extend permission to contain the @Client.Synchronize prop

### CODE REVIEW

**Review by kobergj — APPROVED** [review]

**Comment by butonic** [comment]
This feels redundant. Clients need to safeguard against empty ids anyway. Adding a property only adds conditions clints have to check.

When we change the sharedWithMe endpoint to always contain driveItems with a remoteItem we have to invent a non existing driveItem for an unmounted / unsynced remoteItem. OneDrive actually seems to create an id for those but it has no property to distinguish if a file should be synced or not. Onedrive does not have spaces. It only synchronizes the personal drive. Shares can be synced by adding 'shortcuts' to the shared file in the personal space. In a way the onedrive personal drive is our oc10 user storage with mountpoints. you can even add multiple 'shortcuts' aka mountpoints to the personal drive and move them ito any place you like.

Technically, this is easily possible to do. 'shortcuts' in the personal drive would then implicitly cause a share to be synced. Might be easier to understand than having to manage the synced status of shares ... but collecting them in a dedicated share jail is less confusing.

We can always add 'shortcuts' later.

Back to the issue at hand: using a dedicated property to indicate the synced status. I don't like adding redundancy, especially if it allows more contradictions that we need to test and prevent. What if `id` is empty but `@Client.Synchronize` is `true` or `id` is set but `@Client.Synchronize` is `false`?

I'd not add this property and rather improve the description of the driveItem `id` te explain that it might be empty in the sharedWithMe endpoint ... however ... an empty `id` violates the identifier nature for `driveItems`: `"id": "string (identifier)",` ... 

urgh ... this sucks .... but we cannot really invent a stable idyentifier for non existing drive items. so leave it empty. and document that.

**Comment by fschade** [comment]
as discussed today, '@client.synchronize' and '@ui.hidden' is now part of the remote item

**Review by butonic — APPROVED** [review]

**Comment by rhafer** [comment]
> as discussed today, '@client.synchronize' and '@ui.hidden' is now part of the remote item

I would really love to understand why it was changed that way. Would be really cool if the commit message of the commit making that change contained some reasoning for that.

It is at least conflicting with the idea for grouping multiple share for a single use (e.g. direct share + group share) in a single `remoteItem` as outlined here: https://github.com/owncloud/ocis/pull/8016#issuecomment-1873973545

**Comment by micbar** [comment]
I also don't get that change honestly. When you have more than one share per remote item the hidden and synced states are conflicting.

**Comment by fschade** [comment]
@micbar i agree, that was one of my concerns too, but to be honest, please ask @butonic for details, we discussed it longer and he gave a pretty good explanation why it should be that way...

i just created the pr to be able to continue on the sharedWithMe PR.

**Comment by butonic** [comment]
I remember now. @kulmann @fschade and I decided that the ui property made more sense on the remote item because users do not care about individual permissions. They only care about resources. They don't want to reject permissions. Only resources. Brb

**Pull request merged**
