### PR TITLE
Clean generated directory before we update it

### PR DESCRIPTION
**Pull request by TheOneRing**
Without this step orphaned files will stay forever

### CODE REVIEW

**Comment by TheOneRing** [comment]
Its the approach we use for the desktop translations and it got us rid of 10 year old outdated translations.
However in this case we have a mix of generated code and manually added code.
The repos dont have a common generation dir we could purge so I'm not sure.

For now I could purge the client repo of the c++ bindings, we should really get rid of the binary artifacts from the validation step...
https://github.com/owncloud/libre-graph-api-cpp-qt-client/blob/main/client/libLibreGraphAPI.a

**Comment by fmoc** [comment]
Can't tell whether this approach makes any sense, really. I was not involved in setting this up.

Can the "do not commit generated files" part be fixed by defining ignore patterns very carefully (e.g., by using an allowlist approach rather than the default excludelist one)? Or can we just fix the generator to add support for out-of-source builds?

**Comment by TheOneRing** [comment]
But orphaned files would still remain.

**Comment by TheOneRing** [comment]
We now purge the generated code and copy the licence from the main repo to the generated code.

**Review by micbar — APPROVED** [review]

**Pull request merged**
